name: Dependabot

on:
  pull_request_target:

jobs:
  test:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Test Code
        run: |
          go build -v ./...

  merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    needs: test
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 5
          retry_wait_seconds: 60
          retry_on: error
          command: gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
